development:
  adapter: sqlite3
  database: app.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: app.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: app.db
  pool: 5
  timeout: 5000

